{
  "formatVersion": "1.1",
  "component": {
    "group": "m4gshm",
    "module": "java.timeout",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java.timeout-0.0.1-SNAPSHOT.jar",
          "url": "java.timeout-0.0.1-SNAPSHOT.jar",
          "size": 40497,
          "sha512": "5d06cb6ef2bd9f490278a24106d8c6d9199c54aa2168215c8ec1d0d9563a4b017d3d1478d5a7dbe0d234fe638d62fd2605cf2777e78195fd410c80dd36242a47",
          "sha256": "7a6dfcf2dbdf4c8b273236905dd9225f4c2944bc1a7c2a41adafcef0072d7e3a",
          "sha1": "8b83aeef02ed737c91bdbc172fee3d0cd860d00a",
          "md5": "139a54f5962c1003b0334be2d24de5aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java.timeout-0.0.1-SNAPSHOT.jar",
          "url": "java.timeout-0.0.1-SNAPSHOT.jar",
          "size": 40497,
          "sha512": "5d06cb6ef2bd9f490278a24106d8c6d9199c54aa2168215c8ec1d0d9563a4b017d3d1478d5a7dbe0d234fe638d62fd2605cf2777e78195fd410c80dd36242a47",
          "sha256": "7a6dfcf2dbdf4c8b273236905dd9225f4c2944bc1a7c2a41adafcef0072d7e3a",
          "sha1": "8b83aeef02ed737c91bdbc172fee3d0cd860d00a",
          "md5": "139a54f5962c1003b0334be2d24de5aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java.timeout-0.0.1-SNAPSHOT-sources.jar",
          "url": "java.timeout-0.0.1-SNAPSHOT-sources.jar",
          "size": 16778,
          "sha512": "6935f2e5ce36412d69b8b97c0fba525bdb86509fb1e9346f60788e6ea0cdde3e9cd9e32d7ec70a617535e1e2400de0e8a5458778663568ddd0abc4ff23b47514",
          "sha256": "f1c8e2b1df210cf4437fa5dbac6fe03a00b2a0ec5ff6ecec87e09c88e2a6feeb",
          "sha1": "c3003601b95bcc0ad3bfd73e61174f39d2c1c702",
          "md5": "ce2b4e9c84bf8bed5964a97a43075e36"
        }
      ]
    }
  ]
}
