{
  "formatVersion": "1.1",
  "component": {
    "group": "m4gshm.springframework.boot",
    "module": "spring-boot-ssl-client",
    "version": "0.0.1.SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zoae7opkunck7fh5mehprsaoay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-ssl-client-0.0.1.SNAPSHOT.jar",
          "url": "spring-boot-ssl-client-0.0.1.SNAPSHOT.jar",
          "size": 22304,
          "sha512": "1302422b941b24483d9da61236b8988575787ae1a95ce249466687c212ab1cb3f0db1212646173c8b31aef5ea5f328c75505e9af52b727a9ac7c048b7ddc7b33",
          "sha256": "6b964e355fa82c551aa9e8732e7bd8c397702321ef99ff8059a56cd44c9b3969",
          "sha1": "7c143ba9058e482d8985e694b5e37754003ad0a6",
          "md5": "5c9d468155aab06c20f49bf99cacadc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-ssl-client-0.0.1.SNAPSHOT.jar",
          "url": "spring-boot-ssl-client-0.0.1.SNAPSHOT.jar",
          "size": 22304,
          "sha512": "1302422b941b24483d9da61236b8988575787ae1a95ce249466687c212ab1cb3f0db1212646173c8b31aef5ea5f328c75505e9af52b727a9ac7c048b7ddc7b33",
          "sha256": "6b964e355fa82c551aa9e8732e7bd8c397702321ef99ff8059a56cd44c9b3969",
          "sha1": "7c143ba9058e482d8985e694b5e37754003ad0a6",
          "md5": "5c9d468155aab06c20f49bf99cacadc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-ssl-client-0.0.1.SNAPSHOT-sources.jar",
          "url": "spring-boot-ssl-client-0.0.1.SNAPSHOT-sources.jar",
          "size": 12493,
          "sha512": "f0bf0970a24d127383f42bae3814d02d2e2c429c2f1c24971ff788397a2c87a363d8679778c0640cea4fae1bd227097cd0578f1f56831a9550867d75d8db176e",
          "sha256": "666234e1a8dfcc9d9c62162536edd2e259c6009b00e0143a6b2b7a63d67d8c3b",
          "sha1": "6587780bd00fa034704a6387109646971c963902",
          "md5": "237263acd16ada057a702d0d7f44b6c2"
        }
      ]
    }
  ]
}
